### ISSUE TITLE
Style task list and the style for each task in the list

### ISSUE THREAD

**Issue by keelanburnham** [keelanburnham/taskly#1]
Develop the task list and style how each task looks within the list.

- [x] Write HTML for task list
- [x] Develop CSS for the task list
- [x] Write the HTML for one sample task in the list
- [x] Develop CSS for the one sample task
- [x] Develop two more sample tasks for testing
